name: Checking Format
description: Checking format of C++ files with clang-format
author: jason-ngn

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
